### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by smeinecke** [Brisppy/twitch-archiver#19]
**Describe the bug**
Error download VOD even if its available in browser - could be caused by the fact that the channel has been renamed recently. 

**Supplied arguments**
python3 twitch-archiver.py -d /data/twitch -c lillimon -t 1 -N -D

**Error log**
```
2023-01-23 11:03:38 [    INFO] 1 VOD(s) in download queue.
2023-01-23 11:03:38 [   DEBUG] VOD queue: {40374471912: ('1715379729', True, True)}
2023-01-23 11:03:38 [   DEBUG] Processing VOD 1715379729 by lillimon
2023-01-23 11:03:38 [   DEBUG] Creating lock file for VOD.
2023-01-23 11:03:38 [   DEBUG] Database path: /home/downloader/.config/twitch-archiver/vods.db
2023-01-23 11:03:38 [   DEBUG] Connection to SQLite DB successful.
2023-01-23 11:03:38 [   DEBUG] Executing SQL statement: SELECT vod_id, video_archived, chat_archived FROM vods WHERE stream_id IS ?
2023-01-23 11:03:38 [   DEBUG] Values: {'stream_id': 40374471912}
2023-01-23 11:03:38 [    INFO] Now processing VOD: 1715379729
2023-01-23 11:03:38 [    INFO] VOD offline.
2023-01-23 11:03:39 [    INFO] Grabbing video...
2023-01-23 11:03:40 [ WARNING] Error 403 or 404 returned when downloading VOD parts - VOD was likely deleted.
2023-01-23 11:03:40 [    INFO] Grabbing chat logs...
2023-01-23 11:03:40 [   DEBUG] Grabbing chat logs from offset: 22352
2023-01-23 11:03:41 [    INFO] Found 15 messages.
2023-01-23 11:03:41 [    INFO] Merging VOD parts. This may take a while.
2023-01-23 11:03:41 [   ERROR] Error downloading VOD 1715379729.
Traceback (most recent call last):
  File "/home/downloader/twitch-archiver/src/processing.py", line 394, in get_vod_connector
    Utils.combine_vod_parts(vod_json, print_progress=False if self.quiet else True)
  File "/home/downloader/twitch-archiver/src/utils.py", line 138, in combine_vod_parts
    last_part = int(vod_parts[-1].name.strip('.ts'))
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/downloader/twitch-archiver/src/processing.py", line 401, in get_vod_connector
    raise VodMergeError(e)
src.exceptions.VodMergeError: list index out of range
2023-01-23 11:03:41 [   DEBUG] No VOD information returned to channel function, downloader exited with error.
```

**Operating system**
Linux

**Comment by Brisppy** [comment]
Thanks for the report, the VOD is sub-only which isn't supported yet - I'll add some logging for this.

P.S if someone does have a sub for a sub-only VOD channel and could send their dev.twitch.tv credentials to [me](mailto:brisppy@protonmail.com) I'll work on adding it.

**Comment by smeinecke** [comment]
Oh.. i overlook that, sorry. You could check how https://github.com/besuper/TwitchNoSub does the trick :D

**Comment by Brisppy** [comment]
Interesting, I'll have a look into this.

**Comment by Brisppy** [comment]
Support for subscriber-only VODs added to develop branch with 9265794a.
