### ISSUE TITLE
Time data error when trying to download a vod

### ISSUE THREAD

**Issue by macg2** [Brisppy/twitch-archiver#25]
**Describe the bug**
There was a time data error when trying to download a vod that doesnt match the format in v4.0.0.rc4

**Supplied arguments**
Arguments supplied to twitch-archiver which produced the error.

**Error log**
```
PS D:\Apps\twitch-archiver> twitch-archiver -w -V -c chess --config-dir "D:\Apps\twitch-archiver\Temp\run" -d "D:\Apps\twitch-archiver"
Launching Twitch-Archiver in watch mode.

2024-01-06 12:50:13 [ WARNING] Currently using a development or release candidate build. These may be unfinished or contain serious bugs. Report any issues you encounter to https://github.com/Brisppy/twitch-archiver/issues.
2024-01-06 12:50:13 [    INFO] Twitch Archiver v4.0.0.rc4 - https://github.com/Brisppy/twitch-archiver
2024-01-06 12:50:17 [    INFO] Now archiving channel 'Chess'.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\g2\AppData\Local\Programs\Python\Python312\Scripts\twitch-archiver.exe\__main__.py", line 7, in <module>
  File "C:\Users\g2\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitcharchiver\__init__.py", line 174, in main
    process.get_channel(channels)
  File "C:\Users\g2\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitcharchiver\processing.py", line 69, in get_channel
    channel_videos: list[Vod] = channel.get_channel_videos()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\g2\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitcharchiver\channel.py", line 293, in get_channel_videos
    _videos = [Vod(vod_info=v['node']) for v in _r.json()[0]['data']['user']['videos']['edges']]
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\g2\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitcharchiver\vod.py", line 54, in __init__
    self._parse_dict(vod_info)
  File "C:\Users\g2\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitcharchiver\vod.py", line 105, in _parse_dict
    datetime.strptime(vod_info['publishedAt'], '%Y-%m-%dT%H:%M:%SZ').replace(tzinfo=timezone.utc).timestamp()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\g2\AppData\Local\Programs\Python\Python312\Lib\_strptime.py", line 555, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\g2\AppData\Local\Programs\Python\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2015-07-23T18:51:08.056376Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

**Operating system**
Windows 11

**Additional context**

**Comment by Brisppy** [comment]
Thanks for bringing this to my attention.
Seems to be an issue with older Twitch timestamps, should be fixed now with db823e5468f85563255e71eee001c394f913b23a.
