### ISSUE TITLE
Error occurs if the streamer's name contains CJK language

### ISSUE THREAD

**Issue by PokoChinPoko** [Brisppy/twitch-archiver#26]
**Describe the bug**
If the streamer's name is multibytes, error will occur

**Supplied arguments**
```
twitch-archiver  --archive-only --chat -c dmf_kyochan
```

**Error log**

```
2024-01-16 17:38:26 [    INFO] Twitch Archiver v4.0.1 - https://github.com/Brisppy/twitch-archiver
2024-01-16 17:38:27 [    INFO] Now archiving channel '恭一郎'.
Traceback (most recent call last):
  File "/usr/local/bin/twitch-archiver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/twitcharchiver/__init__.py", line 276, in main
    process.get_channel(channels)
  File "/usr/local/lib/python3.10/dist-packages/twitcharchiver/processing.py", line 74, in get_channel
    channel_videos: list[Vod] = channel.get_channel_videos()
  File "/usr/local/lib/python3.10/dist-packages/twitcharchiver/channel.py", line 351, in get_channel_videos
    for v in _r.json()[0]["data"]["user"]["videos"]["edges"]
TypeError: 'NoneType' object is not subscriptable
```

**[OPTIONAL] Applicable files**
If your issue is related to a VOD video or other file, upload it somewhere and place the link here.

**Operating system**
WSL2
Python 3.10.12

**Additional context**
It worked in version 3, but stopped working after version 4
 functioning is properly if its name does not contain multibytes characters
```
twitch-archiver  --archive-only --chat -c LIRIK
```
```
2024-01-16 17:33:03 [    INFO] Twitch Archiver v4.0.1 - https://github.com/Brisppy/twitch-archiver
2024-01-16 17:33:03 [    INFO] Now archiving channel 'LIRIK'.
2024-01-16 17:33:04 [    INFO] 6 VOD(s) in download queue.
2024-01-16 17:33:04 [    INFO] Skipping VOD as it is live and no-stream argument provided.
2024-01-16 17:33:51 [    INFO] Found 23893 chat messages.
2024-01-16 17:34:49 [    INFO] Found 53907 chat messages.
2024-01-16 17:34:50 [    INFO] Found 57602 chat messages.
  100%  -  [#########################]  -  23692 / 23692  -  ETA: 00:00:00
```

**Comment by Brisppy** [comment]
Thanks for bringing this to my attention, I'll add some tests for non-english channels to avoid this in the future.

Should be fixed now with [v4.0.2](https://github.com/Brisppy/twitch-archiver/releases/tag/v4.0.2).
