### ISSUE TITLE
Error occurs when the stream title is long

### ISSUE THREAD

**Issue by Micheeeel111** [Brisppy/twitch-archiver#27]
**Describe the bug**
Error occurs when the stream title is long

**Supplied arguments**
Arguments supplied to twitch-archiver which produced the error.
```
!twitch-archiver  --archive-only --chat -c ta1yo_tv
```

**Error log**
```
2024-01-17 09:47:37 [    INFO] Twitch Archiver v4.0.2 - https://github.com/Brisppy/twitch-archiver
2024-01-17 10:29:23 [    INFO] Now archiving channel 'ta1yo_tv'.
2024-01-17 10:29:24 [    INFO] 42 VOD(s) in download queue.
Traceback (most recent call last):
  File "/usr/local/bin/twitch-archiver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/twitcharchiver/__init__.py", line 276, in main
    process.get_channel(channels)
  File "/usr/local/lib/python3.10/dist-packages/twitcharchiver/processing.py", line 171, in get_channel
    self.vod_downloader(download_queue)
  File "/usr/local/lib/python3.10/dist-packages/twitcharchiver/processing.py", line 235, in vod_downloader
    _chat_download_queue.append(Chat(_vod, self.output_dir, self.quiet))
  File "/usr/local/lib/python3.10/dist-packages/twitcharchiver/downloaders/chat.py", line 67, in __init__
    self.load_from_file()
  File "/usr/local/lib/python3.10/dist-packages/twitcharchiver/downloaders/chat.py", line 77, in load_from_file
    with open(
OSError: [Errno 36] File name too long: '/content/chats2/ta1yo_tv/2023-12-21_08-38-59 - マウガ実装！！！TOP500実装！！！マウガ実装！！！TOP500実装！！！マウガ実装！！！TOP500実装！！！マウガ実装！！！TOP500実装！！！マウガ実装！！！TOP500実装！！！ - 2009919164/verbose_chat.json'
```

**[OPTIONAL] Applicable files**
If your issue is related to a VOD video or other file, upload it somewhere and place the link here.
```
VOD ID : 2009919164
```
**Operating system**
Colab / Python3.10

**Additional context**
this program is very useful for archiving, thank you for making it
I especially like the  feature to avoid duplicates!

**Comment by Brisppy** [comment]
Thanks for bringing this to my attention, and for the kind words. Problems with long filenames and multibyte characters should be resolved in [v4.0.3](https://github.com/Brisppy/twitch-archiver/releases/latest).
