### ISSUE TITLE
Error while archiving VOD on Twitch

### ISSUE THREAD

**Issue by cscenterr** [Brisppy/twitch-archiver#34]
This problem occurs with all streamers both during live broadcasts and in the process of archiving streams after they've concluded. The error arises when attempting to archive the video, specifically during the merging of video segments, leading to a "VideoMergeError". This issue is not specific to any particular streamer or streaming scenario; it affects all streamers and occurs consistently during both live streams and post-live stream video archiving processes.

vod_id: 2157448619
twitch-archiver -c jeensoff -d "F:\\1" -D --log-dir "F:\\1"

**Error log**
```
2024-05-28 23:51:35 [video.py:362 - _get_ts_segment()] Segment 02473 download completed.
2024-05-28 23:51:35 [utils.py:364 - safe_move()] Moving "C:\Users\dihty\AppData\Local\Temp\twitch-archiver\2157448619\2473.ts" to "F:\1\jeensoff\2024-05-28_16-53-05 - Есть ли шанс пройти моим билдом RFAB Bizarre Adventure _! 😎🤙 - 2157448619\parts\02473.ts".
2024-05-28 23:51:35 [video.py:381 - _get_ts_segment()] Segment 02473 completed and moved to F:\1\jeensoff\2024-05-28_16-53-05 - Есть ли шанс пройти моим билдом RFAB Bizarre Adventure _! 😎🤙 - 2157448619\parts\02473.ts.
2024-05-28 23:51:36 [video.py:362 - _get_ts_segment()] Segment 02475 download completed.
2024-05-28 23:51:36 [utils.py:364 - safe_move()] Moving "C:\Users\dihty\AppData\Local\Temp\twitch-archiver\2157448619\2475.ts" to "F:\1\jeensoff\2024-05-28_16-53-05 - Есть ли шанс пройти моим билдом RFAB Bizarre Adventure _! 😎🤙 - 2157448619\parts\02475.ts".
2024-05-28 23:51:36 [video.py:381 - _get_ts_segment()] Segment 02475 completed and moved to F:\1\jeensoff\2024-05-28_16-53-05 - Есть ли шанс пройти моим билдом RFAB Bizarre Adventure _! 😎🤙 - 2157448619\parts\02475.ts.
2024-05-28 23:51:37 [video.py:362 - _get_ts_segment()] Segment 02476 download completed.
2024-05-28 23:51:37 [utils.py:364 - safe_move()] Moving "C:\Users\dihty\AppData\Local\Temp\twitch-archiver\2157448619\2476.ts" to "F:\1\jeensoff\2024-05-28_16-53-05 - Есть ли шанс пройти моим билдом RFAB Bizarre Adventure _! 😎🤙 - 2157448619\parts\02476.ts".
2024-05-28 23:51:37 [video.py:381 - _get_ts_segment()] Segment 02476 completed and moved to F:\1\jeensoff\2024-05-28_16-53-05 - Есть ли шанс пройти моим билдом RFAB Bizarre Adventure _! 😎🤙 - 2157448619\parts\02476.ts.
2024-05-28 23:51:37 [vod.py:273 - get_chapters()] No chapters found for VOD 2157448619.
2024-05-28 23:51:37 [vod.py:197 - get_category()] Category for VOD 2157448619 is {'id': '1050003477', 'name': 'The Elder Scrolls V: Skyrim - Special Edition'}
2024-05-28 23:51:37 [vod.py:278 - get_chapters()] Chapters generated for VOD based on {'id': '1050003477', 'name': 'The Elder Scrolls V: Skyrim - Special Edition'}: 2157448619
2024-05-28 23:51:37 [video.py:864 - _write_thumbnail()] Downloading VOD thumbnail.
2024-05-28 23:51:39 [video.py:564 - merge()] Merging VOD parts. This may take a while.
2024-05-28 23:52:12 [video.py:567 - merge()] Converting VOD to mp4. This may take a while.
2024-05-28 23:52:13 [video.py:754 - _convert_vod()] FFmpeg exited with error code, output dumped to VOD directory.
2024-05-28 23:52:13 [downloader.py:115 - __exit__()] Exception occurred inside DownloadHandler. ['  File "C:\\Users\\dihty\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\twitcharchiver\\processing.py", line 287, in _start_download\n    _downloader.merge()\n', '  File "C:\\Users\\dihty\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\twitcharchiver\\downloaders\\video.py", line 500, in merge\n    raise VideoMergeError("Exception raised while merging VOD.") from exc\n']
2024-05-28 23:52:13 [processing.py:303 - _start_download()] Error archiving VOD {'vod_id': 2157448619, 'stream_id': 0, 'title': 'Есть ли шанс пройти моим билдом RFAB Bizarre Adventure ?! 😎🤙', 'description': None, 'created_at': datetime.datetime(2024, 5, 28, 13, 53, 5), 'published_at': datetime.datetime(2024, 5, 28, 13, 53, 5), 'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/dgeft87wbj63p/65f639f70b676b094d1f_jeensoff_42391254504_1716904380//thumb/thumb0-90x60.jpg', 'duration': 24770, 'chat_archived': False, 'video_archived': True}.
Traceback (most recent call last):
  File "C:\Users\dihty\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitcharchiver\downloaders\video.py", line 491, in merge
    merger.merge()
  File "C:\Users\dihty\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitcharchiver\downloaders\video.py", line 568, in merge
    self._convert_vod()
  File "C:\Users\dihty\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitcharchiver\downloaders\video.py", line 762, in _convert_vod
    raise VideoConvertError(
twitcharchiver.exceptions.VideoConvertError: VOD converter exited with error. Delete 'parts' directory and re-download VOD.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dihty\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitcharchiver\processing.py", line 287, in _start_download
    _downloader.merge()
  File "C:\Users\dihty\AppData\Local\Programs\Python\Python312\Lib\site-packages\twitcharchiver\downloaders\video.py", line 500, in merge
    raise VideoMergeError("Exception raised while merging VOD.") from exc
twitcharchiver.exceptions.VideoMergeError: Exception raised while merging VOD.

AND FFMPEG.LOG
[in#0 @ 00000143dc753100] Error opening input: Invalid argumentError opening input file 'F:\1\jeensoff\2024-05-28_16-53-05.Error opening input files: Invalid argument
```

**Operating system**
 Windows

**Comment by Brisppy** [comment]
Hi, thanks for opening an issue, this was introduced when trying to fix https://github.com/Brisppy/twitch-archiver/issues/33, I should've run more tests before pushing it.

Can you try the [#develop](https://github.com/Brisppy/twitch-archiver/tree/develop) branch out for me? It should be fixed on there.

**Comment by cscenterr** [comment]
I will attempt to find and download a stream that will be starting from the beginning.

**Comment by Brisppy** [comment]
I see the channel you're archiving doesn't save VODs, unfortunately the stream only archiver is still not entirely reliable. I'll add them to my testing server and see if there's anything which can be done to help.

**Comment by cscenterr** [comment]
Thank you for looking into it. I understand that the stream-only archiver can be challenging. Your effort is greatly appreciated, and your utility has been immensely helpful

**Comment by LEMON67** [comment]
I have a similar problem when archiving a non-vod stream. The .ts files seem to be missing small chunks of the stream which seem to cause issues for twitch-archiver when merging them. I can merge them myself then convert to an mp4 but the small bits and pieces of the stream that are missing are pretty annoying. I am really happy with the other functions and love the fast updates to problems that I've seen.
![temp](https://github.com/Brisppy/twitch-archiver/assets/60624493/17fcb8a5-283a-43c6-aa18-252c802c5071)

**Comment by Brisppy** [comment]
Yeah I've been struggling with how to tackle this, one of the main problems is ads along with occasional segment corruption. When ads are playing they stop sending stream segments to you, so pre-roll ads prevent the first 30 or so seconds from being grabbed and midrolls will take up chunks throughout. Without a VOD to downloading the missing parts there isn't much to be done (outside of trying to circumvent the ads somehow).

**Comment by LEMON67** [comment]
Would it be easier to set up authentication so If you are subbed to a channel you can apply that in the twitch-archiver somehow? Instead of bypassing the ads

**Comment by Brisppy** [comment]
Could definitely work, would need to do some testing with a subbed account not sure how they pass authentication.

**Comment by Brisppy** [comment]
Implemented with [v4.3.0](https://github.com/Brisppy/twitch-archiver/releases).
