### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by nelson-wu** [Brisppy/twitch-archiver#41]
**Describe the bug**
DownloadHandler throwing exception on newly beginning stream.

**Supplied arguments**
`$ twitch-archiver -w -l -c iosys_os`

**Error log**
```
2024-12-29 00:53:17 [    INFO] iosys_os is offline and `live-only` argument provided.
2024-12-29 00:53:27 [    INFO] Now archiving channel 'iosys_os'.
2024-12-29 00:53:27 [    INFO] Stream began very recently, buffering initial segments until API updates.
2024-12-29 00:54:23 [   ERROR] Failed to update chapters for stream. Error: 'NoneType' object is not subscriptable
2024-12-29 00:54:23 [   ERROR] Exception occurred inside DownloadHandler. ['  File "/home/fujiko/.local/share/virtualenvs/twitch_vods-NWHkHxag/lib/python3.11/site-packages/twitcharchiver/processing.py", line 326, in _start_download\n    _downloader.start()\n', '  File "/home/fujiko/.local/share/virtualenvs/twitch_vods-NWHkHxag/lib/python3.11/site-packages/twitcharchiver/downloaders/stream.py", line 303, in start\n    if self._check_stream_ended():\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/home/fujiko/.local/share/virtualenvs/twitch_vods-NWHkHxag/lib/python3.11/site-packages/twitcharchiver/downloaders/stream.py", line 461, in _check_stream_ended\n    self._get_final_segment()\n', '  File "/home/fujiko/.local/share/virtualenvs/twitch_vods-NWHkHxag/lib/python3.11/site-packages/twitcharchiver/downloaders/stream.py", line 688, in _get_final_segment\n    max(self._completed_segments, key=attrgetter("id")).id + 1\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n']
2024-12-29 00:54:23 [   ERROR] Error archiving VOD {'vod_id': 0, 'stream_id': 0, 'title': '', 'description': '', 'created_at': datetime.datetime(1970, 1, 1, 0, 0), 'published_at': datetime.datetime(1970, 1, 1, 0, 0), 'thumbnail_url': '', 'duration': 1735451616, 'chat_archived': False, 'video_archived': False}.
Traceback (most recent call last):
  File "/home/fujiko/.local/share/virtualenvs/twitch_vods-NWHkHxag/lib/python3.11/site-packages/twitcharchiver/processing.py", line 326, in _start_download
    _downloader.start()
  File "/home/fujiko/.local/share/virtualenvs/twitch_vods-NWHkHxag/lib/python3.11/site-packages/twitcharchiver/downloaders/stream.py", line 303, in start
    if self._check_stream_ended():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fujiko/.local/share/virtualenvs/twitch_vods-NWHkHxag/lib/python3.11/site-packages/twitcharchiver/downloaders/stream.py", line 461, in _check_stream_ended
    self._get_final_segment()
  File "/home/fujiko/.local/share/virtualenvs/twitch_vods-NWHkHxag/lib/python3.11/site-packages/twitcharchiver/downloaders/stream.py", line 688, in _get_final_segment
    max(self._completed_segments, key=attrgetter("id")).id + 1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
```

**[OPTIONAL] Applicable files**
If your issue is related to a VOD video or other file, upload it somewhere and place the link here.

**Operating system**
WSL 2
Ubuntu 20.04.2 LTS

**Additional context**
Another simultaneous stream download with the same command on a different channel completed successfully.

**Comment by Brisppy** [comment]
Thanks for opening an issue. It's a bit hard to tell what happened without debug logs or past broadcasts available, but most likely they started their stream and ended it before the pre-roll ad(s) were finished. I'll add a check and some logging for this in case it happens in the future.

**Comment by nelson-wu** [comment]
Thanks for taking a look. I'll run it with debug logging next time to see if it repros again.

**Comment by Brisppy** [comment]
I pushed a change to the [develop](https://github.com/Brisppy/twitch-archiver/tree/develop) branch which should prevent this exception from being raised if you wouldn't mind trying that.
