### ISSUE TITLE
IndexError on skip-live-streams

### ISSUE THREAD

**Issue by smeinecke** [Brisppy/twitch-archiver#5]
**Describe the bug**
Missing check on parameter `-N` if channel_data is returned

**Supplied arguments**
`python3 twitch-archiver.py -d /data/twitch -c lillimontv -t 1 -N`

**Error log**
```
2022-12-06 22:34:41 [    INFO] Twitch Archiver v2.2.0 - https://github.com/Brisppy/twitch-archiver
2022-12-06 22:34:42 [    INFO] OAuth token verified successfully. Expiring in 5075700
2022-12-06 22:34:43 [    INFO] Now archiving channel 'lillimontv'.
2022-12-06 22:34:44 [    INFO] Online VODs: 22
2022-12-06 22:34:44 [    INFO] Downloaded vods: 17
2022-12-06 22:34:44 [    INFO] 5 VOD(s) in download queue.
Traceback (most recent call last):
  File "twitch-archiver.py", line 41, in <module>
    main()
  File "/root/twitch-archiver/src/__init__.py", line 142, in main
    process.get_channel(args.get('channel'))
  File "/root/twitch-archiver/src/processing.py", line 209, in get_channel
    elif self.no_stream and stream_id == int(channel_data[0]['id']):
IndexError: list index out of range
```

**Operating system**
Debian 11

**Comment by Brisppy** [comment]
Thanks for catching this and making a PR, ill merge this into the develop branch with some other fixes on the way.
