### ISSUE TITLE
Errors on download for specific video

### ISSUE THREAD

**Issue by koroban** [Brisppy/twitch-archiver#8]
**Describe the bug**
Somehow this video produces many status-code received errors. But works fine if downloaded by yt-dlp from the same machine/IP.

**Supplied arguments**
`python3 twitch-archiver.py -v 1647999281 -t 4 -V -D`

**Error log**
```
2022-12-08 00:39:46 [   DEBUG] Arguments: {'channel': None, 'vod_id': ['1647999281'], 'client_id': None, 'client_secret': None, 'chat': False, 'video': True, 'threads': 4, 'quality': 'best', 'directory': PosixPath('/root/twitch-archiver'), 'watch': False, 'stream_only': False, 'no_stream': False, 'log_file': False, 'config_dir': PosixPath('/root/.config/twitch-archiver'), 'pushbullet_key': False, 'quiet': 0, 'debug': 10, 'show_config': False}
2022-12-08 00:39:46 [    INFO] Twitch Archiver v2.2.1 - https://github.com/Brisppy/twitch-archiver
2022-12-08 00:39:46 [   DEBUG] Loading config from file.
2022-12-08 00:39:46 [   DEBUG] Settings prior to loading config: {'client_id': '************************25qogj', 'client_secret': '************************wqgoh0', 'oauth_token': '************************stgjwt', 'pushbullet_key': ''}
2022-12-08 00:39:46 [   DEBUG] Generating config from provided arguments.
2022-12-08 00:39:46 [   DEBUG] Settings after loading config: {'client_id': '************************25qogj', 'client_secret': '************************wqgoh0', 'oauth_token': '************************stgjwt', 'pushbullet_key': ''}
2022-12-08 00:39:46 [   DEBUG] Performing Twitch authentication.
2022-12-08 00:39:46 [   DEBUG] Verifying OAuth token.
2022-12-08 00:39:47 [    INFO] OAuth token verified successfully. Expiring in 4981795
2022-12-08 00:39:47 [    INFO] Now processing VOD: 1647999281
2022-12-08 00:39:47 [    INFO] VOD offline.
2022-12-08 00:39:48 [    INFO] Grabbing video...
2022-12-08 00:39:49 [   DEBUG] Downloading segment https://d1ymi26ma8va5x.cloudfront.net/6f122e645c399a4e0051_lillimontv_40054216216_1668018595/chunked/3492.ts to /root/twitch-archiver/2022-11-09_18-30-00 - AMOGUS mit _wer_ __ FSK18 _ __merch __nitrado __klazmo __tiktok __dn - 1647999281/parts/03492.ts
2022-12-08 00:39:49 [   DEBUG] Downloading segment https://d1ymi26ma8va5x.cloudfront.net/6f122e645c399a4e0051_lillimontv_40054216216_1668018595/chunked/3493.ts to /root/twitch-archiver/2022-11-09_18-30-00 - AMOGUS mit _wer_ __ FSK18 _ __merch __nitrado __klazmo __tiktok __dn - 1647999281/parts/03493.ts
2022-12-08 00:39:49 [   DEBUG] Downloading segment https://d1ymi26ma8va5x.cloudfront.net/6f122e645c399a4e0051_lillimontv_40054216216_1668018595/chunked/3494.ts to /root/twitch-archiver/2022-11-09_18-30-00 - AMOGUS mit _wer_ __ FSK18 _ __merch __nitrado __klazmo __tiktok __dn - 1647999281/parts/03494.ts
2022-12-08 00:39:49 [   DEBUG] Downloading segment https://d1ymi26ma8va5x.cloudfront.net/6f122e645c399a4e0051_lillimontv_40054216216_1668018595/chunked/3495.ts to /root/twitch-archiver/2022-11-09_18-30-00 - AMOGUS mit _wer_ __ FSK18 _ __merch __nitrado __klazmo __tiktok __dn - 1647999281/parts/03495.ts
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   ERROR] Code other than 200 received when trying to download segment.
2022-12-08 00:39:49 [   DEBUG] Maximum retries for segment 03495 reached.
```

**Operating system**
Ubuntu 20.04

**Additional context**
Also tried to reduce thread count to 1, removed part files and tried again later - same error. Happens for multiple VODs by multiple different streamers, but not all the time and persistent for the same videos/chunks.

**Comment by koroban** [comment]
Wow, thanks for that fast fix. Yep, download of VoD is working fine now :+1: 

Also, the download of chats works now. I just had the problem (probably because I canceled the download prematurely by killing the script) that it gives the following error when resuming the chat download:

```
2022-12-09 00:22:29 [    INFO] 1 VOD(s) in download queue.
2022-12-09 00:22:29 [    INFO] Now processing VOD: 1671991485
2022-12-09 00:22:29 [    INFO] VOD offline.
2022-12-09 00:22:30 [    INFO] Grabbing chat logs...
2022-12-09 00:22:30 [   ERROR] Error downloading VOD 1671991485.
Traceback (most recent call last):
  File "/root/twitch-archiver/src/processing.py", line 572, in get_vod
    elif int(chat_log[-1]['contentOffsetSeconds']) < vod_json['duration']:
KeyError: 'contentOffsetSeconds'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/twitch-archiver/src/processing.py", line 384, in get_vod_connector
    self.get_vod(vod_json, get_video, get_chat, vod_live)
  File "/root/twitch-archiver/src/processing.py", line 589, in get_vod
    raise ChatDownloadError(e)
src.exceptions.ChatDownloadError: 'contentOffsetSeconds'
```

**Comment by Brisppy** [comment]
Yeah I did encounter that, its because they altered some of the backend keys, easy fix is to just delete any 'verbose_chat.log' files created with the old version. If this doesn't work though let me know.

**Comment by koroban** [comment]
Yep, works fine, thank you again! :) And thanks for this project! :D I already automated my downloads with yt-dlp + simple bash script for the chat, but this sooo much better!
