### ISSUE TITLE
More metadata

### ISSUE THREAD

**Issue by koroban** [Brisppy/twitch-archiver#9]
Is it possible to extract more metadata of the VoD? As far as I know yt-dlp extracts additionally chapters (change of the title / change of game) by timestamp.

Also an additional parameter to the script to download the thumbnail(s) would be great so it's possible to show a gallery with thumbnails of all downloaded streams - like on archive.org.

**Comment by Brisppy** [comment]
Thumbnail and VOD chapter retrieval / inclusion in the output video is now included in the [develop](https://github.com/Brisppy/twitch-archiver/tree/develop) branch for testing.

**Comment by koroban** [comment]
Thank you for the feature!

I just tested this and I got following recurring error:

_commandline:_
`/usr/bin/python3 /home/downloader/twitch-archiver/twitch-archiver.py -d /data/twitch -c kimtnt -N -w`

```
Dec 23 10:52:33 twitchdl python3[2881]: 2022-12-23 10:52:33 [    INFO] Now processing VOD: 1686047377
Dec 23 10:52:34 twitchdl python3[2881]: 2022-12-23 10:52:34 [    INFO] VOD offline.
Dec 23 10:52:34 twitchdl python3[2881]: 2022-12-23 10:52:34 [    INFO] Grabbing video...
Dec 23 10:57:02 twitchdl python3[2881]: [48.0K blob data]
Dec 23 10:58:04 twitchdl python3[2881]: [28.1K blob data]
Dec 23 10:58:04 twitchdl python3[2881]: --- Logging error ---
Dec 23 10:58:04 twitchdl python3[2881]: Traceback (most recent call last):
Dec 23 10:58:04 twitchdl python3[2881]:   File "/home/downloader/twitch-archiver/src/processing.py", line 409, in get_vod_connector
Dec 23 10:58:04 twitchdl python3[2881]:     chapters_file.write(Utils.format_vod_chapters(vod_chapters))
Dec 23 10:58:04 twitchdl python3[2881]:   File "/home/downloader/twitch-archiver/src/utils.py", line 573, in format_vod_chapters
Dec 23 10:58:04 twitchdl python3[2881]:     title=chapter['details']['game']['displayName'])
Dec 23 10:58:04 twitchdl python3[2881]: TypeError: 'NoneType' object is not subscriptable
Dec 23 10:58:04 twitchdl python3[2881]: During handling of the above exception, another exception occurred:
Dec 23 10:58:04 twitchdl python3[2881]: Traceback (most recent call last):
Dec 23 10:58:04 twitchdl python3[2881]:   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
Dec 23 10:58:04 twitchdl python3[2881]:     msg = self.format(record)
Dec 23 10:58:04 twitchdl python3[2881]:   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
Dec 23 10:58:04 twitchdl python3[2881]:     return fmt.format(record)
Dec 23 10:58:04 twitchdl python3[2881]:   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
Dec 23 10:58:04 twitchdl python3[2881]:     record.message = record.getMessage()
Dec 23 10:58:04 twitchdl python3[2881]:   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
Dec 23 10:58:04 twitchdl python3[2881]:     msg = msg % self.args
Dec 23 10:58:04 twitchdl python3[2881]: TypeError: not all arguments converted during string formatting
Dec 23 10:58:04 twitchdl python3[2881]: Call stack:
Dec 23 10:58:04 twitchdl python3[2881]:   File "/home/downloader/twitch-archiver/twitch-archiver.py", line 41, in <module>
Dec 23 10:58:04 twitchdl python3[2881]:     main()
Dec 23 10:58:04 twitchdl python3[2881]:   File "/home/downloader/twitch-archiver/src/__init__.py", line 142, in main
Dec 23 10:58:04 twitchdl python3[2881]:     process.get_channel(args.get('channel'))
Dec 23 10:58:04 twitchdl python3[2881]:   File "/home/downloader/twitch-archiver/src/processing.py", line 233, in get_channel
Dec 23 10:58:04 twitchdl python3[2881]:     vod_json = self.get_vod_connector(vod_id, vod_queue[stream_id][1], vod_queue[stream_id][2])
Dec 23 10:58:04 twitchdl python3[2881]:   File "/home/downloader/twitch-archiver/src/processing.py", line 412, in get_vod_connector
Dec 23 10:58:04 twitchdl python3[2881]:     self.log.error('Failed to retrieve or insert chapters into VOD file.', e)
Dec 23 10:58:04 twitchdl python3[2881]: Message: 'Failed to retrieve or insert chapters into VOD file.'
Dec 23 10:58:04 twitchdl python3[2881]: Arguments: (TypeError("'NoneType' object is not subscriptable"),)
Dec 23 10:58:04 twitchdl python3[2881]: 2022-12-23 10:58:04 [    INFO] Merging VOD parts. This may take a while.
```

Already deleted parts folder + retry to download the VoD. Any idea? Other videos works fine :)

**Comment by Brisppy** [comment]
Thanks for catching that, should be fixed as of the new #develop version. That particular VOD had a chapter with no game attached which didn't come up in my testing.

**Comment by koroban** [comment]
Thank you for your help! Yes. works fine now :+1:
